// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AreaCascader: typeof import('./src/components/areaCascader/areaCascader.vue')['default']
    CommonForm: typeof import('./src/components/CommonForm/index.vue')['default']
    CommonSelect: typeof import('./src/components/CommonTable/CommonSelect.vue')['default']
    CommonTable: typeof import('./src/components/CommonTable/index.vue')['default']
    DebounceTest: typeof import('./src/components/jsDemo/debounceTest.vue')['default']
    DeepClone: typeof import('./src/components/jsDemo/deepClone.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    HelloWorld: typeof import('./src/components/jsDemo/HelloWorld.vue')['default']
    Index_old: typeof import('./src/components/CommonForm/index_old.vue')['default']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    MarqueeX: typeof import('./src/components/marquee/marqueeX.vue')['default']
    TableTitle: typeof import('./src/components/CommonTable/TableTitle.vue')['default']
    TabsForm: typeof import('./src/components/TabsForm/index.vue')['default']
    ThrottleTest: typeof import('./src/components/jsDemo/throttleTest.vue')['default']
  }
}

export { }
